# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# set working dir
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json tsup.config.ts ./
RUN npm ci

# Copy source and build
COPY src ./src
RUN npm run build

# Remove dev dependencies
RUN npm prune --production

# Expose port if HTTP, but this is stdio

CMD ["node", "dist/index.js"]
